/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PluginOptions {
  name: string
  buildStart?: () => Promise<void>
  resolveId?: (
    specifier: string,
    importer?: string,
  ) => Promise<undefined | ResolveIdResult>
  load?: (id: string) => Promise<undefined | SourceResult>
  transform?: (id: string, code: string) => Promise<undefined | SourceResult>
  buildEnd?: (error: string) => Promise<void>
}
export interface ResolveIdResult {
  id: string
  external?: boolean
}
export interface SourceResult {
  code: string
}
export interface InputItem {
  name?: string
  import: string
}
export interface InputOptions {
  input: Array<InputItem>
  plugins: Array<PluginOptions>
  cwd: string
}
export interface OutputOptions {
  entryFileNames?: string
  chunkFileNames?: string
  dir?: string
  exports?: 'default' | 'named' | 'none' | 'auto'
  format?: 'esm' | 'cjs'
}
export interface OutputChunk {
  code: string
  fileName: string
}
export class Bundler {
  constructor(inputOpts: InputOptions)
  write(opts: OutputOptions): Promise<Array<OutputChunk>>
  generate(opts: OutputOptions): Promise<Array<OutputChunk>>
}
