use crate::types::generator::{GenerateContext, GenerateOutput, Generator};

use anyhow::Result;
use rolldown_common::{
  Chunk, CssAssetMeta, InstantiatedChunk, InstantiationKind, RollupRenderedChunk,
};
use rolldown_error::BuildResult;
use rolldown_sourcemap::{SourceJoiner, SourceMapSource};
use string_wizard::SourceMapOptions;

pub struct CssGenerator;

// ref: crates/rolldown/src/utils/chunk/mod.rs -> generate_rendered_chunk
fn generate_css_rendered_chunk(chunk: &Chunk) -> RollupRenderedChunk {
  let pre_rendered_chunk =
    chunk.pre_rendered_chunk.as_ref().expect("Should have pre-rendered chunk");

  let filename =
    chunk.css_preliminary_filename.as_deref().expect("should have preliminary_filename").clone();

  RollupRenderedChunk {
    name: pre_rendered_chunk.name.clone(),
    is_entry: pre_rendered_chunk.is_entry,
    is_dynamic_entry: pre_rendered_chunk.is_dynamic_entry,
    facade_module_id: pre_rendered_chunk.facade_module_id.clone(),
    module_ids: pre_rendered_chunk.module_ids.clone(), // contains js module ids
    exports: pre_rendered_chunk.exports.clone(),

    // seems we only use these 2 fields for css
    filename,
    debug_id: 0,

    // not used
    modules: Default::default(),
    imports: Default::default(),
    dynamic_imports: Default::default(),
  }
}

impl Generator for CssGenerator {
  #[allow(clippy::too_many_lines)]
  async fn instantiate_chunk<'a>(
    ctx: &mut GenerateContext<'a>,
  ) -> Result<BuildResult<GenerateOutput>> {
    let mut ordered_css_modules = ctx
      .chunk
      .modules
      .iter()
      .filter_map(|&id| ctx.link_output.module_table.modules[id].as_normal())
      .filter(|m| m.css_view.is_some())
      .collect::<Vec<_>>();

    if ordered_css_modules.is_empty() {
      return Ok(Ok(GenerateOutput {
        chunks: vec![],
        warnings: std::mem::take(&mut ctx.warnings),
      }));
    }

    ordered_css_modules.sort_by_key(|m| m.exec_order);

    let mut source_joiner = SourceJoiner::default();

    let enable_sourcemap = ctx.options.sourcemap.is_some();
    source_joiner.enable_sourcemap = enable_sourcemap;

    for module in &ordered_css_modules {
      let css_view = module.css_view.as_ref().unwrap();
      let mut magic_string = string_wizard::MagicString::new(&css_view.source);
      for mutation in &css_view.mutations {
        mutation.apply(&mut magic_string);
      }

      if enable_sourcemap {
        let content = magic_string.to_string();
        let mut sourcemap = magic_string.source_map(SourceMapOptions::default());
        sourcemap.set_sources(vec![&module.stable_id]);
        let source = SourceMapSource::new(content, sourcemap).with_pre_compute_sourcemap_data(true);
        source_joiner.append_source(source);
      } else {
        source_joiner.append_source(magic_string.to_string());
      }
    }

    let (content, map) = source_joiner.join();

    // Here file path is generated by chunk file name template, it maybe including path segments.
    // So here need to read it's parent directory as file_dir.
    let file_path = ctx.options.cwd.as_path().join(&ctx.options.dir).join(
      ctx
        .chunk
        .css_preliminary_filename
        .as_deref()
        .expect("chunk file name should be generated before rendering")
        .as_str(),
    );
    let file_dir = file_path.parent().expect("chunk file name should have a parent");

    let rendered_chunk = generate_css_rendered_chunk(ctx.chunk);

    Ok(Ok(GenerateOutput {
      chunks: vec![InstantiatedChunk {
        origin_chunk: ctx.chunk_idx,
        content: content.into(),
        map,
        kind: InstantiationKind::from(CssAssetMeta { rendered_chunk }),
        augment_chunk_hash: None,
        file_dir: file_dir.to_path_buf(),
        preliminary_filename: ctx
          .chunk
          .css_preliminary_filename
          .clone()
          .expect("should have preliminary filename"),
      }],
      warnings: std::mem::take(&mut ctx.warnings),
    }))
  }
}
