export { default as foo1 } from "./foo1"
export { default as foo2 } from "./foo2"
export { default as foo3 } from "./foo3"
export { default as foo4 } from "./foo4"
export { default as bar1 } from "./bar1"
export { default as bar2 } from "./bar2"
export { default as bar3 } from "./bar3"
export { default as bar4 } from "./bar4"
export { default as baz1 } from "./baz1"
export { default as baz2 } from "./baz2"
import "./outer"