// cSpell:disable
// // Aligned with rollup

// pub const ADDON_ERROR: &str = "ADDON_ERROR";
// pub const ALREADY_CLOSED: &str = "ALREADY_CLOSED";
// pub const AMBIGUOUS_EXTERNAL_NAMESPACES: &str = "AMBIGUOUS_EXTERNAL_NAMESPACES";
// pub const ANONYMOUS_PLUGIN_CACHE: &str = "ANONYMOUS_PLUGIN_CACHE";
// pub const ASSET_NOT_FINALISED: &str = "ASSET_NOT_FINALISED";
// pub const ASSET_NOT_FOUND: &str = "ASSET_NOT_FOUND";
// pub const ASSET_SOURCE_ALREADY_SET: &str = "ASSET_SOURCE_ALREADY_SET";
// pub const ASSET_SOURCE_MISSING: &str = "ASSET_SOURCE_MISSING";
// pub const BAD_LOADER: &str = "BAD_LOADER";
// pub const CANNOT_CALL_NAMESPACE: &str = "CANNOT_CALL_NAMESPACE";
// pub const CANNOT_EMIT_FROM_OPTIONS_HOOK: &str = "CANNOT_EMIT_FROM_OPTIONS_HOOK";
// pub const CHUNK_NOT_GENERATED: &str = "CHUNK_NOT_GENERATED";
// pub const CHUNK_INVALID: &str = "CHUNK_INVALID";
// pub const CIRCULAR_DEPENDENCY: &str = "CIRCULAR_DEPENDENCY";
// pub const CIRCULAR_REEXPORT: &str = "CIRCULAR_REEXPORT";
// pub const CYCLIC_CROSS_CHUNK_REEXPORT: &str = "CYCLIC_CROSS_CHUNK_REEXPORT";
// pub const DEPRECATED_FEATURE: &str = "DEPRECATED_FEATURE";
// pub const DUPLICATE_IMPORT_OPTIONS: &str = "DUPLICATE_IMPORT_OPTIONS";
// pub const DUPLICATE_PLUGIN_NAME: &str = "DUPLICATE_PLUGIN_NAME";
// pub const EMPTY_BUNDLE: &str = "EMPTY_BUNDLE";
// pub const EVAL: &str = "EVAL";
// pub const EXTERNAL_SYNTHETIC_EXPORTS: &str = "EXTERNAL_SYNTHETIC_EXPORTS";
// pub const FAIL_AFTER_WARNINGS: &str = "FAIL_AFTER_WARNINGS";
// pub const FILE_NAME_CONFLICT: &str = "FILE_NAME_CONFLICT";
// pub const FILE_NOT_FOUND: &str = "FILE_NOT_FOUND";
// pub const ILLEGAL_IDENTIFIER_AS_NAME: &str = "ILLEGAL_IDENTIFIER_AS_NAME";
// pub const ILLEGAL_REASSIGNMENT: &str = "ILLEGAL_REASSIGNMENT";
// pub const INCONSISTENT_IMPORT_ASSERTIONS: &str = "INCONSISTENT_IMPORT_ASSERTIONS";
// pub const INPUT_HOOK_IN_OUTPUT_PLUGIN: &str = "INPUT_HOOK_IN_OUTPUT_PLUGIN";
// pub const INVALID_CHUNK: &str = "INVALID_CHUNK";
// pub const INVALID_CONFIG_MODULE_FORMAT: &str = "INVALID_CONFIG_MODULE_FORMAT";
// pub const INVALID_EXPORT_OPTION: &str = "INVALID_EXPORT_OPTION";
// pub const INVALID_EXTERNAL_ID: &str = "INVALID_EXTERNAL_ID";
// pub const INVALID_OPTION: &str = "INVALID_OPTION";
// pub const INVALID_PLUGIN_HOOK: &str = "INVALID_PLUGIN_HOOK";
// pub const INVALID_ROLLUP_PHASE: &str = "INVALID_ROLLUP_PHASE";
// pub const INVALID_SETASSETSOURCE: &str = "INVALID_SETASSETSOURCE";
// pub const INVALID_TLA_FORMAT: &str = "INVALID_TLA_FORMAT";
// pub const MISSING_CONFIG: &str = "MISSING_CONFIG";
// pub const MISSING_EXPORT: &str = "MISSING_EXPORT";
// pub const MISSING_EXTERNAL_CONFIG: &str = "MISSING_EXTERNAL_CONFIG";
// pub const MISSING_GLOBAL_NAME: &str = "MISSING_GLOBAL_NAME";
// pub const MISSING_IMPLICIT_DEPENDANT: &str = "MISSING_IMPLICIT_DEPENDANT";
// pub const MISSING_NAME_OPTION_FOR_IIFE_EXPORT: &str = "MISSING_NAME_OPTION_FOR_IIFE_EXPORT";
// pub const MISSING_NODE_BUILTINS: &str = "MISSING_NODE_BUILTINS";
// pub const MISSING_OPTION: &str = "MISSING_OPTION";
// pub const MIXED_EXPORTS: &str = "MIXED_EXPORTS";
// pub const MODULE_LEVEL_DIRECTIVE: &str = "MODULE_LEVEL_DIRECTIVE";
// pub const NAMESPACE_CONFLICT: &str = "NAMESPACE_CONFLICT";
// pub const NO_FS_IN_BROWSER: &str = "NO_FS_IN_BROWSER";
// pub const NO_TRANSFORM_MAP_OR_AST_WITHOUT_CODE: &str = "NO_TRANSFORM_MAP_OR_AST_WITHOUT_CODE";
// pub const ONLY_INLINE_SOURCEMAPS: &str = "ONLY_INLINE_SOURCEMAPS";
// pub const PARSE_ERROR: &str = "PARSE_ERROR";
// pub const PLUGIN_ERROR: &str = "PLUGIN_ERROR";
// pub const SHIMMED_EXPORT: &str = "SHIMMED_EXPORT";
// pub const SOURCEMAP_BROKEN: &str = "SOURCEMAP_BROKEN";
pub const SOURCEMAP_ERROR: &str = "SOURCEMAP_ERROR";
// pub const SYNTHETIC_NAMED_EXPORTS_NEED_NAMESPACE_EXPORT: &str =
//   "SYNTHETIC_NAMED_EXPORTS_NEED_NAMESPACE_EXPORT";
// pub const THIS_IS_UNDEFINED: &str = "THIS_IS_UNDEFINED";
// pub const UNEXPECTED_NAMED_IMPORT: &str = "UNEXPECTED_NAMED_IMPORT";
// pub const UNKNOWN_OPTION: &str = "UNKNOWN_OPTION";
pub const UNRESOLVED_ENTRY: &str = "UNRESOLVED_ENTRY";
pub const UNRESOLVED_IMPORT: &str = "UNRESOLVED_IMPORT";
// pub const UNUSED_EXTERNAL_IMPORT: &str = "UNUSED_EXTERNAL_IMPORT";
// pub const VALIDATION_ERROR: &str = "VALIDATION_ERROR";

// // Rolldown error codes

// pub const PANIC: &str = "PANIC";
pub const IO_ERROR: &str = "IO_ERROR";
