namespace ns {
	export var MANGLE_VAR_ = 1
	export let MANGLE_LET_ = 2
	export const MANGLE_CONST_ = 3
	export let { NESTED_: { DESTRUCTURING_ } } = 4
	export function MANGLE_FUNCTION_() {}
	export class MANGLE_CLASS_ {}
	export namespace MANGLE_NAMESPACE_ { ; }
	export enum MANGLE_ENUM_ {}

	console.log({
		VAR: MANGLE_VAR_,
		LET: MANGLE_LET_,
		CONST: MANGLE_CONST_,
		DESTRUCTURING: DESTRUCTURING_,
		FUNCTION: MANGLE_FUNCTION_,
		CLASS: MANGLE_CLASS_,
		NAMESPACE: MANGLE_NAMESPACE_,
		ENUM: MANGLE_ENUM_,
	})
}

console.log({
	VAR: ns.MANGLE_VAR_,
	LET: ns.MANGLE_LET_,
	CONST: ns.MANGLE_CONST_,
	DESTRUCTURING: ns.DESTRUCTURING_,
	FUNCTION: ns.MANGLE_FUNCTION_,
	CLASS: ns.MANGLE_CLASS_,
	NAMESPACE: ns.MANGLE_NAMESPACE_,
	ENUM: ns.MANGLE_ENUM_,
})

namespace ns {
	console.log({
		VAR: MANGLE_VAR_,
		LET: MANGLE_LET_,
		CONST: MANGLE_CONST_,
		DESTRUCTURING: DESTRUCTURING_,
		FUNCTION: MANGLE_FUNCTION_,
		CLASS: MANGLE_CLASS_,
		NAMESPACE: MANGLE_NAMESPACE_,
		ENUM: MANGLE_ENUM_,
	})
}