import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{createPortal}from"react-dom";import{useRef,useState,useEffect,forwardRef}from"react";import{AnimatePresence,motion}from"framer-motion";import{SearchIcon}from"https://framerusercontent.com/modules/LV9trClbmNwd5PVj9l8y/L4rFqMGNzGSwRZpGTGF3/Icons.js";import{addPropertyControls,ControlType,RenderTarget,withCSS}from"framer";import{SearchModal,SearchResultItemType,SearchResultTitleType,SearchResultSubtitleType,SearchInputDividerType,SearchInputClearButtonType,SearchLayoutType,SearchIconType}from"https://framerusercontent.com/modules/tV9haTHllpHHc9Fjue2H/Xy775u0FJg3K1GQc1Cd9/SearchModal.js";import{useViewportSizeState}from"https://framerusercontent.com/modules/hqEf5wXaAewP8VPuaZ98/5A0QGVeEr2cwheQpIuEG/useViewportSizeState.js";import{titleCase,DEFAULT_FONT_FAMILY,isEmptyObject,animationKeyFromLayout,checkIfOverLimit}from"https://framerusercontent.com/modules/MWsEnYfRnoOQq31DN4ql/C71JVnvNwV2CrPvApXBB/utils.js";import{Browser}from"https://framerusercontent.com/modules/PJVBcBLmDteTEAZh3J9Z/keXJyjyE9VnzUcDMayjg/browser.js";var EntryPointOptions;// SITE SEARCH
// By Anthony and Hunter
(function(EntryPointOptions){EntryPointOptions["icon"]="Icon";EntryPointOptions["input"]="Input";})(EntryPointOptions||(EntryPointOptions={}));function buildShadow(shadowProperty,fallback="none"){if(!shadowProperty)return fallback;const{x,y,blur,color,spread}=shadowProperty;return`${x}px ${y}px ${blur}px ${spread}px ${color}`;}const Overlay=/*#__PURE__*/forwardRef(function Overlay(props,ref){const{layoutType,theme,onDismiss}=props;useEffect(()=>{const handleKeyDown=event=>{if(event.code==="Escape"){event.stopPropagation();onDismiss();}};const handlePointerDown=event=>{if(event.pointerType!=="touch")return;const isWithinSearchHeader=Boolean(event.target instanceof Element&&event.target.closest("[role=search]"));if(isWithinSearchHeader)return;if(document.activeElement instanceof HTMLInputElement){document.activeElement.blur();}};// Event listener added to window so that pressing escape key to dimiss
// can be invoked from anywhere on the page.
window.addEventListener("keydown",handleKeyDown);window.addEventListener("pointerdown",handlePointerDown,{capture:true});// Disable page scrolling when overlay is shown.
document.body.classList.add(bodyOverflowHidden);return()=>{window.removeEventListener("keydown",handleKeyDown);window.removeEventListener("pointerdown",handlePointerDown,{capture:true});document.body.classList.remove(bodyOverflowHidden);};},[]);return /*#__PURE__*/createPortal(/*#__PURE__*/_jsxs("div",{ref:ref,className:"__framer-search-modal-container",role:"presentation",style:{...backdropStyles,zIndex:props.backdropOptions.zIndex,justifyContent:layoutType===SearchLayoutType.Sidebar?"flex-start":"center"},onClick:onDismiss,children:[/*#__PURE__*/_jsx(motion.div,{role:"presentation",initial:{opacity:0},animate:{opacity:1},exit:{opacity:0,transition:{duration:0}},transition:theme.overlayTransition,style:{top:0,left:0,right:0,bottom:0,width:"100%",height:"100%",boxSizing:"border-box",position:"absolute",touchAction:"none",backgroundColor:props.backdropOptions.backgroundColor}}),/*#__PURE__*/_jsx(SearchModal,{urlScope:props.urlScope,layoutType:layoutType,inputOptions:props.inputOptions,resultOptions:props.resultOptions,modalOptions:props.modalOptions,backdropOptions:props.backdropOptions,theme:props.theme,onDismiss:onDismiss})]}),document.body);});const backdropStyles={width:"100%",boxSizing:"border-box",willChange:"transform",position:"fixed",display:"flex",alignItems:"flex-start",top:0,left:0,right:0,bottom:0};const containerStyle={height:"100%",display:"flex",borderRadius:10,cursor:"inherit",overflow:"hidden"};const bodyOverflowHidden="__framer-overflow-hidden";/**
 *
 * SEARCH
 * By Anthony and Hunter
 *
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 *
 * @framerDisableUnlink
 *
 * @framerIntrinsicWidth 40
 * @framerIntrinsicHeight 40
 */const EntryPoint=withCSS(function EntryPoint(props){var _props_inputOptions_inputFont,_props_inputOptions,_props_resultOptions,_props_resultOptions_subtitleOptions,_props_inputOptions1;const overlay=useRef(null);const[isOpen,setIsOpen]=useState(false);const[isOverLimit,setIsOverLimit]=useState(false);const[isSafariTouchDevice,setIsSafariTouchDevice]=useState(false);const[isOnCanvas]=useState(()=>RenderTarget.current()===RenderTarget.canvas);useEffect(()=>{setIsOverLimit(checkIfOverLimit());setIsSafariTouchDevice(Browser.isSafari()&&Browser.isTouch());},[]);const baseInputFontSize=((_props_inputOptions=props.inputOptions)===null||_props_inputOptions===void 0?void 0:(_props_inputOptions_inputFont=_props_inputOptions.inputFont)===null||_props_inputOptions_inputFont===void 0?void 0:_props_inputOptions_inputFont.fontSize)?props.inputOptions.inputFont.fontSize:"16px";// The font size is set to a minimum of `16px` on Safari with touch screens
// because otherwise Safari will zoom in slightly if the type size is smaller.
const inputFontSize=isSafariTouchDevice?`max(16px, ${baseInputFontSize})`:baseInputFontSize;const layoutType=useViewportSizeState(size=>{if(size.width<props.modalOptions.width+10){return SearchLayoutType.FixedTop;}// @ts-ignore – Fallback
return props.modalOptions.layoutType||props.layoutType;});const theme={subtitleColor:props.resultOptions.subtitleOptions.subtitleColor,backgroundColor:props.modalOptions.backgroundColor,foregroundColor:props.resultOptions.titleColor,placeholderColor:props.inputOptions.placeholderOptions.placeholderColor,titleFont:((_props_resultOptions=props.resultOptions)===null||_props_resultOptions===void 0?void 0:_props_resultOptions.titleFont)&&!isEmptyObject(props.resultOptions.titleFont)?props.resultOptions.titleFont:{fontSize:14,fontFamily:DEFAULT_FONT_FAMILY,fontWeight:500},subtitleFont:((_props_resultOptions_subtitleOptions=props.resultOptions.subtitleOptions)===null||_props_resultOptions_subtitleOptions===void 0?void 0:_props_resultOptions_subtitleOptions.subtitleFont)&&!isEmptyObject(props.resultOptions.subtitleOptions.subtitleFont)?props.resultOptions.subtitleOptions.subtitleFont:{fontSize:12,fontFamily:DEFAULT_FONT_FAMILY,fontWeight:500},inputFont:((_props_inputOptions1=props.inputOptions)===null||_props_inputOptions1===void 0?void 0:_props_inputOptions1.inputFont)&&!isEmptyObject(props.inputOptions.inputFont)?props.inputOptions.inputFont:{fontSize:16,fontFamily:DEFAULT_FONT_FAMILY,fontWeight:500},// Keep separate so we can more easily override
inputFontSize:inputFontSize,width:props.modalOptions.width,offsetTop:props.modalOptions.top,borderRadius:props.modalOptions.borderRadius,shadow:buildShadow(props.modalOptions.shadow),entryIconColor:props.iconColor,entryIconSize:props.iconSize,entryIconImage:props.iconImage,inputIconSize:props.inputOptions.iconOptions.iconSize,inputIconColor:props.inputOptions.iconOptions.iconColor,inputIconImage:props.inputOptions.iconOptions.iconImage,gapBetweenStatusAndSearch:16,gapBetweenResults:1,scrollBarWidth:20,margin:10,spacing:8,zIndex:props.backdropOptions.zIndex,horizontalSpacing:20,overlayTransition:props.backdropOptions.transition};const handleClick=event=>{// Both need to keep `autofocus` working on the search input.
event.preventDefault();event.stopPropagation();if(isOverLimit)return;setIsOpen(true);};return /*#__PURE__*/_jsxs("div",{style:{...containerStyle,...props.style,pointerEvents:isOverLimit?"none":"auto",opacity:isOverLimit?.4:1},children:[/*#__PURE__*/_jsx("button",{"aria-label":"Search Icon",style:{width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",background:"none",cursor:"inherit",color:"inherit",border:"none",outline:"inherit",padding:0},onClick:handleClick,children:props.iconType===SearchIconType.Custom&&theme.entryIconImage?/*#__PURE__*/_jsx("img",{alt:"icon entry point for Site Search",src:theme.entryIconImage.src,width:theme.entryIconSize,height:theme.entryIconSize}):/*#__PURE__*/_jsx(SearchIcon,{color:theme.entryIconColor,width:theme.entryIconSize,height:theme.entryIconSize})}),/*#__PURE__*/_jsx(AnimatePresence,{children:isOpen&&!isOnCanvas&&/*#__PURE__*/_jsx(Overlay,{ref:overlay,layoutType:layoutType,urlScope:props.urlScope,inputOptions:props.inputOptions,resultOptions:props.resultOptions,backdropOptions:props.backdropOptions,modalOptions:props.modalOptions,theme:theme,onDismiss:()=>setIsOpen(false)})})]});},[// Prevent scrolling on iOS Safari when Input is focused.
// From: https://gist.github.com/kiding/72721a0553fa93198ae2bb6eefaa3299
`
        @keyframes __framer-blink-input {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        .__framer-search-modal-container input:focus {
            animation: __framer-blink-input 0.01s;
        }
        `,// Allow styling of input placeholder
`
         .__framer-search-modal-container input::placeholder, 
         .__framer-search-modal-container input::-webkit-input-placeholder { 
            color: var(--framer-search-placeholder-color, #999999);
            opacity: 1;
        }
        `,// Allow fallback to 100vh when dvh unit is not supported.
`
        .__framer-search-modal-container {
            height: 100vh;
            height: 100dvh;
        }
        .__framer-search-modal-container .__framer-max-height-80dvh {
            max-height: 80vh;
            max-height: 80dvh;
        }
        `,`
        body.${bodyOverflowHidden} {
            overflow: hidden;
        }`,// Increase hit target
`
        button.__framer-search-clear-button {
            position: relative;
        }
        button.__framer-search-clear-button::after {
            content: "";
            position: absolute;
            top: -10px;
            right: -10px;
            bottom: -10px;
            left: -10px;
        }`]);export default EntryPoint;addPropertyControls(EntryPoint,{urlScope:{title:"Scope",// @ts-ignore - Internal
type:ControlType.PageScope},// entryType: {
//     title: "Type",
//     type: ControlType.Enum,
//     options: Object.values(SearchEntryType),
//     optionTitles: Object.values(SearchEntryType).map(titleCase),
//     displaySegmentedControl: true,
// },
iconType:{title:"Icon",type:ControlType.Enum,options:Object.values(SearchIconType),optionTitles:Object.values(SearchIconType).map(titleCase),displaySegmentedControl:true},iconColor:{title:"Color",type:ControlType.Color,defaultValue:"#333",hidden:props=>props.iconType===SearchIconType.Custom},iconImage:{title:"File",type:ControlType.ResponsiveImage,allowedFileTypes:["jpg","png","svg"],hidden:props=>props.iconType===SearchIconType.Default},iconSize:{title:"Size",type:ControlType.Number,displayStepper:true,defaultValue:24},inputOptions:{title:"Input",type:ControlType.Object,buttonTitle:"Icon, Styles",controls:{iconOptions:{title:"Icon",type:ControlType.Object,buttonTitle:"Color, Size",controls:{iconType:{title:"Icon",type:ControlType.Enum,options:Object.values(SearchIconType),optionTitles:Object.values(SearchIconType).map(titleCase),displaySegmentedControl:true},iconColor:{title:"Color",type:ControlType.Color,defaultValue:"rgba(0, 0, 0, 0.45)",hidden:({iconType})=>{return iconType===SearchIconType.Custom;}},iconImage:{title:"File",type:ControlType.ResponsiveImage,allowedFileTypes:["jpg","png","svg"],hidden:({iconType})=>iconType===SearchIconType.Default},iconSize:{title:"Icon Size",type:ControlType.Number,displayStepper:true,defaultValue:18,min:0,max:100}}},inputFont:{title:"Font",// @ts-ignore – Internal
type:ControlType.Font,displayFontSize:true},textColor:{title:"Color",type:ControlType.Color,defaultValue:"#333"},placeholderOptions:{title:"Placeholder",type:ControlType.Object,buttonTitle:"Color, Text",controls:{placeholderText:{title:"Text",type:ControlType.String,defaultValue:"Search..."},placeholderColor:{title:"Color",type:ControlType.Color,defaultValue:"rgba(0,0,0,0.4)"}}},dividerType:{title:"Divider",type:ControlType.Enum,options:Object.values(SearchInputDividerType),optionTitles:Object.keys(SearchInputDividerType).map(titleCase),defaultValue:SearchInputDividerType.FullWidth},clearButtonType:{title:"Clear Type",type:ControlType.Enum,options:Object.values(SearchInputClearButtonType),optionTitles:Object.keys(SearchInputClearButtonType).map(titleCase),defaultValue:SearchInputClearButtonType.Icon},clearButtonText:{title:"Clear Text",type:ControlType.String,defaultValue:"Clear",hidden:props=>props.clearButtonType!==SearchInputClearButtonType.Text}}},modalOptions:{title:"Modal",buttonTitle:"Layout, Width",type:ControlType.Object,controls:{layoutType:{title:"Layout",type:ControlType.Enum,options:Object.keys(SearchLayoutType),optionTitles:Object.values(SearchLayoutType).map(titleCase),defaultValue:SearchLayoutType.QuickMenu},width:{title:"Width",type:ControlType.Number,defaultValue:500,min:200,max:1e3,displayStepper:true,step:5,hidden:props=>props.layoutType===SearchLayoutType.FixedTop},top:{title:"Top",type:ControlType.Number,defaultValue:0,min:0,max:1e3,displayStepper:true,hidden:props=>props.layoutType!==SearchLayoutType.FixedTop},heightIsStatic:{title:"Height",type:ControlType.Boolean,enabledTitle:"Instant",disabledTitle:"Animate",hidden:({layoutType})=>layoutType!==SearchLayoutType.QuickMenu},heightTransition:{title:"Type",type:ControlType.Transition,defaultValue:{type:"spring",stiffness:800,damping:60},hidden:({heightIsStatic,layoutType})=>layoutType!==SearchLayoutType.QuickMenu||heightIsStatic},borderRadius:{title:"Radius",type:ControlType.Number,defaultValue:16,displayStepper:true,min:0,hidden:({layoutType})=>layoutType!==SearchLayoutType.QuickMenu},shadow:{buttonTitle:"Options",type:ControlType.Object,defaultValue:{x:0,y:20,blur:40,spread:0,color:"rgba(0,0,0,0.2)"},controls:{color:{type:ControlType.Color,defaultValue:"rgba(0,0,0,0.2)"},x:{type:ControlType.Number,defaultValue:0},y:{type:ControlType.Number,defaultValue:20},blur:{type:ControlType.Number,defaultValue:40},spread:{type:ControlType.Number,defaultValue:0}}},backgroundColor:{title:"Background",type:ControlType.Color,defaultValue:"#FFF"},[animationKeyFromLayout(SearchLayoutType.QuickMenu)]:{title:"Animation",type:ControlType.Object,icon:"effect",hidden:({layoutType})=>layoutType!==SearchLayoutType.QuickMenu,optional:true,buttonTitle:"Options",controls:{opacity:{type:ControlType.Number,defaultValue:.5,step:.1,min:0,max:1},scale:{type:ControlType.Number,defaultValue:.75,step:.1,min:0,max:2},// rotate: {
//     type: ControlType.Number,
//     defaultValue: 0,
//     min: -360,
//     max: 360,
// },
x:{type:ControlType.Number,defaultValue:0,min:-500,max:500},y:{type:ControlType.Number,defaultValue:0,min:-500,max:500},transition:{type:ControlType.Transition}}},[animationKeyFromLayout(SearchLayoutType.FixedTop)]:{title:"Animation",type:ControlType.Object,icon:"effect",buttonTitle:"Options",hidden:({layoutType})=>layoutType!==SearchLayoutType.FixedTop,optional:true,controls:{opacity:{type:ControlType.Number,defaultValue:.8,step:.1,min:0,max:1},y:{type:ControlType.Number,defaultValue:0,min:-100,max:100},transition:{type:ControlType.Transition}}},[animationKeyFromLayout(SearchLayoutType.Sidebar)]:{title:"Animation",type:ControlType.Object,icon:"effect",buttonTitle:"Options",hidden:({layoutType})=>layoutType!==SearchLayoutType.Sidebar,optional:true,controls:{opacity:{type:ControlType.Number,defaultValue:.8,step:.1,min:0,max:1},x:{type:ControlType.Number,defaultValue:0,min:-1e3,max:1e3},transition:{type:ControlType.Transition}}}}},resultOptions:{title:"Results",buttonTitle:"Fonts, Style",type:ControlType.Object,defaultValue:{},// description:
//     "Learn more about how to use Site Search [here](https://framer.com/learn/site-search)",
controls:{itemType:{title:"Style",type:ControlType.Enum,options:Object.values(SearchResultItemType),optionTitles:Object.keys(SearchResultItemType).map(titleCase),defaultValue:SearchResultItemType.FullWidth},titleFont:{title:"Title",// @ts-ignore - Internal
type:ControlType.Font,defaultValue:{fontSize:15},displayFontSize:true},titleColor:{title:"Color",type:ControlType.Color,defaultValue:"#333"},titleType:{title:"Content",type:ControlType.Enum,options:Object.values(SearchResultTitleType),optionTitles:Object.keys(SearchResultTitleType).map(titleCase),defaultValue:SearchResultTitleType.H1,displaySegmentedControl:true},subtitleOptions:{type:ControlType.Object,title:"Subtitle",buttonTitle:"Font, Content",controls:{subtitleFont:{title:"Font",// @ts-ignore - Internal
type:ControlType.Font,defaultValue:{fontSize:13},displayFontSize:true},subtitleColor:{title:"Color",type:ControlType.Color,defaultValue:"rgba(0, 0, 0, 0.4)"},subtitleType:{title:"Content",type:ControlType.Enum,options:Object.values(SearchResultSubtitleType),optionTitles:Object.keys(SearchResultSubtitleType).map(titleCase),defaultValue:SearchResultSubtitleType.Path}}}}},backdropOptions:{title:"Backdrop",type:ControlType.Object,buttonTitle:"Color, Z Index",controls:{backgroundColor:{title:"Color",type:ControlType.Color,defaultValue:"rgba(0, 0, 0, 0.8)"},zIndex:{title:"Z Index",type:ControlType.Number,defaultValue:10,displayStepper:true,min:0,max:10},transition:{type:ControlType.Transition}}}});EntryPoint.displayName="Search";
export const __FramerMetadata__ = {"exports":{"ResponsiveImage":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"Shadow":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"default":{"type":"reactComponent","name":"EntryPoint","slots":[],"annotations":{"framerSupportedLayoutWidth":"any-prefer-fixed","framerIntrinsicHeight":"40","framerContractVersion":"1","framerSupportedLayoutHeight":"any-prefer-fixed","framerDisableUnlink":"*","framerIntrinsicWidth":"40"}},"EntryPointProps":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"WindowAnimation":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}