const y0 = Symbol.for(undefined)
const y1 = Symbol.for(null)
const y2 = Symbol.for(true)
const y3 = Symbol.for(123)
const y4 = Symbol.for(123n)
const y5 = Symbol.for('abc')
const y6 = Symbol.for(/* @__PURE__ */ (() => Math.random() < 0.5)() ? 'x' : 'y')

const n0 = Symbol.for()
const n1 = Symbol.for({})
const n2 = Symbol.for(/./)
const n3 = Symbol.for(() => 0)
const n4 = Symbol.for(x)
const n5 = new Symbol.for('abc')
const n6 = Symbol.for(1, 2, 3)
const n7 = Symbol.for((() => Math.random() < 0.5)() ? 'x' : 'y')