import { defineConfig } from 'rolldown';
import { moduleFederationPlugin } from 'rolldown/experimental';

export default defineConfig({
  input: './index.jsx',
  plugins: [
    moduleFederationPlugin({
      name: 'mf-host',
      remotes: {
        rolldown: 'http://localhost:8085/mf-manifest.json',
        // generated by https://github.com/rolldown/rolldown-mf-webpack-remote
        webpack:
          'webpack@https://unpkg.com/rolldown-mf-webpack-remote@1.0.0/dist/remoteEntry.js',
      },
      shared: {
        react: {
          singleton: true,
        },
      },
    }),
    {
      name: 'emit-html',
      generateBundle() {
        const html = `
          <html>
            <body>
              <div id="app"></div>
              <script type="module" src="./index.js"></script>
            </body>
          </html>
        `;
        this.emitFile({
          type: 'asset',
          fileName: 'index.html',
          source: html,
        });
      },
    },
  ],
});
