import './pick-js.js'
import './pick-ts.js'
import './pick-jsx.jsx'
import './pick-tsx.jsx'
import './order-js.js'
import './order-jsx.jsx'

import 'pkg/foo-js.js'
import 'pkg/foo-jsx.jsx'
import 'pkg-exports/xyz-js'
import 'pkg-exports/xyz-jsx'
import 'pkg-exports/foo-js.js'
import 'pkg-exports/foo-jsx.jsx'
import 'pkg-imports'