const source = `
    test_tests__esbuild__dce__const_value_inlining_bundle__config_json
    test_tests__esbuild__dce__const_value_inlining_direct_eval__config_json
    test_tests__esbuild__dce__const_value_inlining_no_bundle__config_json
    test_tests__esbuild__dce__dce_class_static_blocks_minify_syntax__config_json
    test_tests__esbuild__dce__dce_of_decorators__config_json
    test_tests__esbuild__dce__dce_of_experimental_decorators__config_json
    test_tests__esbuild__dce__dce_of_expr_after_keep_names_issue3195__config_json
    test_tests__esbuild__dce__dce_of_iife__config_json
    test_tests__esbuild__dce__dce_type_of_compare_string_guard_condition__config_json
    test_tests__esbuild__dce__dce_type_of_equals_string_guard_condition__config_json
    test_tests__esbuild__dce__dead_code_following_jump__config_json
    test_tests__esbuild__dce__drop_labels__config_json
    test_tests__esbuild__dce__inline_empty_function_calls__config_json
    test_tests__esbuild__dce__inline_function_call_behavior_changes__config_json
    test_tests__esbuild__dce__inline_identity_function_calls__config_json
    test_tests__esbuild__dce__multiple_declaration_tree_shaking_minify_syntax__config_json
    test_tests__esbuild__dce__nested_function_inlining_with_spread__config_json
    test_tests__esbuild__dce__no_side_effects_comment_ignore_annotations__config_json
    test_tests__esbuild__dce__no_side_effects_comment_minify_whitespace__config_json
    test_tests__esbuild__dce__no_side_effects_comment_unused_calls__config_json
    test_tests__esbuild__dce__preserve_directives_minify_bundle__config_json
    test_tests__esbuild__dce__preserve_directives_minify_iife__config_json
    test_tests__esbuild__dce__pure_calls_with_spread__config_json
    test_tests__esbuild__dce__remove_unused_no_side_effects_tagged_templates__config_json
    test_tests__esbuild__dce__top_level_function_inlining_with_spread__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_export_star_side_effects_false__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_export_star_side_effects_false_only_js__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_re_export_side_effects_false__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_re_export_side_effects_false_only_js__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_unused_nested_import_side_effects_false__config_json
    test_tests__esbuild__dce__tree_shaking_js_with_associated_css_unused_nested_import_side_effects_false_only_js__config_json
    test_tests__esbuild__dce__tree_shaking_lowered_class_static_field__config_json
    test_tests__esbuild__dce__tree_shaking_lowered_class_static_field_assignment__config_json
    test_tests__esbuild__dce__tree_shaking_lowered_class_static_field_minified__config_json

`

const trimmed = source.trim()
let lines = trimmed.split('\n')

for (let line of lines) {
  const caseName = line.trim().slice(26, -13)
  console.log(`caseName: `, caseName)
}



