const y0 = Symbol()
const y1 = Symbol(undefined)
const y2 = Symbol(null)
const y3 = Symbol(true)
const y4 = Symbol(123)
const y5 = Symbol(123n)
const y6 = Symbol('abc')
const y7 = Symbol(/* @__PURE__ */ (() => Math.random() < 0.5)() ? 'x' : 'y')

const n0 = Symbol({})
const n1 = Symbol(/./)
const n2 = Symbol(() => 0)
const n3 = Symbol(x)
const n4 = new Symbol('abc')
const n5 = Symbol(1, 2, 3)
const n6 = Symbol((() => Math.random() < 0.5)() ? 'x' : 'y')