// napi-rs-artifact-metadata:{"version":2,"rootEntry":"binding.cjs","exports":["LegalCommentsMode","minify","minifySync","Severity","ParseResult","ExportExportNameKind","ExportImportNameKind","ExportLocalNameKind","ImportNameKind","parse","parseSync","rawTransferSupported","ResolverFactory","EnforceExtension","ModuleType","sync","HelperMode","isolatedDeclaration","isolatedDeclarationSync","moduleRunnerTransform","moduleRunnerTransformSync","transform","transformSync","BindingAsyncRuntimeLease","BindingBundleEndEventData","BindingBundleErrorEventData","BindingBundler","BindingBundleStartEventData","BindingCallableBuiltinPlugin","BindingChunkingContext","BindingDecodedMap","BindingDevEngine","BindingLoadPluginContext","BindingMagicString","BindingModuleInfo","BindingNormalizedOptions","BindingOutputAsset","BindingOutputChunk","BindingPluginContext","BindingRenderedChunk","BindingRenderedChunkMeta","BindingRenderedModule","BindingSourceMap","BindingTransformPluginContext","BindingWatcher","BindingWatcherBundler","BindingWatcherChangeData","BindingWatcherEvent","ParallelJsPluginRegistry","TraceSubscriberGuard","TsconfigCache","acquireAsyncRuntime","BindingAttachDebugInfo","BindingBuiltinPluginName","BindingChunkModuleOrderBy","BindingErrorStage","BindingLogLevel","BindingPluginOrder","BindingPropertyReadSideEffects","BindingPropertyWriteSideEffects","BindingRebuildStrategy","BindingRuntimeFlavor","collapseSourcemaps","configureAsyncRuntime","enhancedTransform","enhancedTransformSync","FilterTokenKind","getAsyncRuntimeConfig","getAsyncRuntimeMetrics","getCurrentThreadTaskHostContractVersion","getRuntimeCapabilities","initTraceSubscriber","isCurrentThreadHostRegistrationActive","registerCurrentThreadTaskHost","registerPlugins","registerTimerHost","reserveCurrentThreadHostRegistration","resetAsyncRuntimeMetrics","resolveTsconfig","shutdownAsyncRuntime","startAsyncRuntime","unregisterCurrentThreadTaskHost","unregisterTimerHost"],"managedRootEntries":["browser.js","binding.cjs","rolldown-binding.wasm","rolldown-binding.debug.wasm"]}
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')

const {
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')
const { createContext: __emnapiCreateContext } = require('@emnapi/runtime')


const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

function __captureEmnapiAutoDestroyListener() {
  if (
    typeof process.prependListener !== 'function' ||
    typeof process.removeListener !== 'function'
  ) {
    return
  }
  let __autoDestroyListener
  const __captureListener = (__event, __listener) => {
    if (__event === 'beforeExit' && __autoDestroyListener === undefined) {
      __autoDestroyListener = __listener
    }
  }
  try {
    // Run before existing newListener hooks so a hook that registers its own
    // beforeExit listener cannot be mistaken for emnapi's registration.
    process.prependListener('newListener', __captureListener)
  } catch {
    return
  }
  return () => {
    try {
      process.removeListener('newListener', __captureListener)
    } catch {}
    if (__autoDestroyListener !== undefined) {
      try {
        process.removeListener('beforeExit', __autoDestroyListener)
      } catch {}
    }
  }
}

const __finishAutoDestroyCapture = __captureEmnapiAutoDestroyListener()
let __emnapiContext
let __napiInstance
let __emnapiContextDestroyed = false
let __emnapiContextDestroying = false
let __emnapiContextDestroyPromise
let __emnapiContextRegisteredForBeforeExit = false
let __emnapiContextRegisteredForExit = false
let __emnapiContextBeforeExitRegistrationRetryCount = 0
let __emnapiContextBeforeExitRegistrationRetryScheduled = false
let __contextInitializationError
let __contextInitializationFailed = false
try {
  __emnapiContext = __emnapiCreateContext({ autoDestroy: false })
  // emnapi <= 1.11 ignores autoDestroy. suppressDestroy() is the public
  // contract that keeps this context alive until our explicit cleanup runs.
  __emnapiContext.suppressDestroy()
} catch (error) {
  __contextInitializationError = error
  __contextInitializationFailed = true
} finally {
  // Remove only the exact legacy callback captured above. suppressDestroy()
  // remains the safety net if listener removal is unavailable or fails.
  __finishAutoDestroyCapture?.()
}

let __emnapiWasmEnvCleanupPrepared = false

if (__emnapiContext !== undefined) {
  // A raw destroy call on the emnapi context (bypassing
  // __destroyEmnapiContext) must still settle pending napi async work: run
  // the wasm-side cleanup preparation while the environment can still call
  // into JavaScript, then delegate to the original destroy.
  // oxlint-disable-next-line typescript/unbound-method -- invoked with the wrapper receiver below
  const __emnapiContextDestroy = __emnapiContext.destroy
  __emnapiContext.destroy = function() {
    if (!__emnapiWasmEnvCleanupPrepared) {
      const __prepareWasmEnvCleanup =
        __napiInstance?.exports?.napi_prepare_wasm_env_cleanup
      if (typeof __prepareWasmEnvCleanup === 'function') {
        __prepareWasmEnvCleanup()
      }
      __emnapiWasmEnvCleanupPrepared = true
    }
    return Reflect.apply(__emnapiContextDestroy, this, arguments)
  }
}

function __destroyEmnapiContext() {
  if (__emnapiContextDestroyed) {
    return
  }
  if (__emnapiContextDestroyPromise) {
    return __emnapiContextDestroyPromise
  }
  if (__emnapiContextDestroying) {
    return
  }
  __emnapiContextDestroying = true
  let __result
  try {
    if (!__emnapiWasmEnvCleanupPrepared) {
      const __prepareWasmEnvCleanup =
        __napiInstance?.exports?.napi_prepare_wasm_env_cleanup
      if (typeof __prepareWasmEnvCleanup === 'function') {
        __prepareWasmEnvCleanup()
      }
      __emnapiWasmEnvCleanupPrepared = true
    }
    __result = __emnapiContext.destroy()
  } catch (error) {
    __emnapiContextDestroying = false
    throw error
  }
  let __then
  try {
    if (
      __result !== null &&
      (typeof __result === 'object' || typeof __result === 'function')
    ) {
      __then = __result.then
    }
  } catch (error) {
    __emnapiContextDestroying = false
    throw error
  }
  if (typeof __then === 'function') {
    let __resolveResult
    let __rejectResult
    const __resultPromise = new Promise((resolve, reject) => {
      __resolveResult = resolve
      __rejectResult = reject
    })
    const __promise = __resultPromise.then(
      (value) => {
        __emnapiContextDestroying = false
        __emnapiContextDestroyed = true
        __emnapiContextDestroyPromise = undefined
        return value
      },
      (error) => {
        __emnapiContextDestroying = false
        __emnapiContextDestroyPromise = undefined
        throw error
      },
    )
    __emnapiContextDestroyPromise = __promise
    try {
      Reflect.apply(__then, __result, [__resolveResult, __rejectResult])
    } catch (error) {
      __rejectResult(error)
    }
    return __promise
  }
  __emnapiContextDestroying = false
  __emnapiContextDestroyed = true
}

function __removeEmnapiContextBeforeExitListener() {
  if (__emnapiContextRegisteredForBeforeExit) {
    process.removeListener('beforeExit', __destroyEmnapiContextBeforeExit)
    __emnapiContextRegisteredForBeforeExit = false
  }
}

function __removeEmnapiContextAtExitListener() {
  if (__emnapiContextRegisteredForExit) {
    process.removeListener('exit', __destroyEmnapiContextAtExit)
    __emnapiContextRegisteredForExit = false
  }
}

function __removeEmnapiContextCleanupListeners() {
  const __errors = []
  try {
    __removeEmnapiContextBeforeExitListener()
  } catch (__error) {
    __errors.push(__error)
  }
  try {
    __removeEmnapiContextAtExitListener()
  } catch (__error) {
    __errors.push(__error)
  }
  if (__errors.length === 0) {
    __emnapiContextBeforeExitRegistrationRetryCount = 0
    return
  }
  if (__errors.length === 1) {
    throw __errors[0]
  }
  throw new AggregateError(
    __errors,
    'emnapi context cleanup listener removal failed',
  )
}

function __scheduleEmnapiContextBeforeExitRegistration() {
  if (
    __emnapiContextDestroyed ||
    __emnapiContextRegisteredForBeforeExit ||
    __emnapiContextBeforeExitRegistrationRetryScheduled ||
    __emnapiContextBeforeExitRegistrationRetryCount >= 3
  ) {
    return
  }
  __emnapiContextBeforeExitRegistrationRetryScheduled = true
  __emnapiContextBeforeExitRegistrationRetryCount++
  queueMicrotask(() => {
    __emnapiContextBeforeExitRegistrationRetryScheduled = false
    if (
      __emnapiContextDestroyed ||
      __emnapiContextRegisteredForBeforeExit
    ) {
      return
    }
    try {
      __registerEmnapiContextBeforeExit()
    } catch {}
  })
}

function __registerEmnapiContextBeforeExit() {
  if (!__emnapiContextRegisteredForBeforeExit) {
    try {
      process.once('beforeExit', __destroyEmnapiContextBeforeExit)
    } catch (error) {
      __scheduleEmnapiContextBeforeExitRegistration()
      throw error
    }
    __emnapiContextRegisteredForBeforeExit = true
    __emnapiContextBeforeExitRegistrationRetryCount = 0
  }
}

function __registerEmnapiContextAtExit() {
  if (!__emnapiContextRegisteredForExit) {
    process.once('exit', __destroyEmnapiContextAtExit)
    __emnapiContextRegisteredForExit = true
  }
}

function __retainEmnapiContextCleanupListener() {
  if (
    __emnapiContextDestroyed ||
    __emnapiContextRegisteredForBeforeExit ||
    __emnapiContextRegisteredForExit
  ) {
    return
  }
  __registerEmnapiContextBeforeExit()
}

function __handoffEmnapiContextCleanupToExit() {
  const __exitWasRegistered = __emnapiContextRegisteredForExit
  __registerEmnapiContextAtExit()
  try {
    __removeEmnapiContextBeforeExitListener()
  } catch (__error) {
    if (!__exitWasRegistered) {
      try {
        __removeEmnapiContextAtExitListener()
      } catch (__rollbackError) {
        throw new AggregateError(
          [__error, __rollbackError],
          'emnapi context cleanup listener handoff failed',
          { cause: __error },
        )
      }
    }
    throw __error
  }
}

function __destroyEmnapiContextBeforeExit() {
  __emnapiContextRegisteredForBeforeExit = false
  let __result
  try {
    __result = __destroyEmnapiContext()
  } catch (error) {
    try {
      __registerEmnapiContextBeforeExit()
    } catch {}
    queueMicrotask(() => {
      throw error
    })
    return
  }
  if (__result) {
    void __result.then(
      () => {
        __removeEmnapiContextCleanupListeners()
      },
      (error) => {
        try {
          __registerEmnapiContextBeforeExit()
        } catch {}
        queueMicrotask(() => {
          throw error
        })
      },
    )
  } else {
    __removeEmnapiContextCleanupListeners()
  }
}

function __destroyEmnapiContextAtExit() {
  __emnapiContextRegisteredForExit = false
  try {
    const __result = __destroyEmnapiContext()
    if (__result) {
      void __result.catch(() => {})
    }
  } catch {}
}

function __attachCleanupError(__error, __cleanupError) {
  try {
    if (
      __error &&
      (typeof __error === 'object' || typeof __error === 'function')
    ) {
      if (__error.cause === undefined) {
        __error.cause = __cleanupError
        return __error.cause === __cleanupError
      }
      return __error.cause === __cleanupError
    }
  } catch {}
  return false
}

function __preserveCleanupError(__error, __cleanupError) {
  if (!__attachCleanupError(__error, __cleanupError)) {
    queueMicrotask(() => {
      throw __cleanupError
    })
  }
}

if (__contextInitializationFailed) {
  let __registrationError
  let __registrationFailed = false
  if (__emnapiContext !== undefined) {
    try {
      __registerEmnapiContextBeforeExit()
    } catch (error) {
      __preserveCleanupError(__contextInitializationError, error)
      __registrationError = error
      __registrationFailed = true
    }
    let __cleanupResult
    let __cleanupFailed = false
    try {
      __cleanupResult = __destroyEmnapiContext()
    } catch (error) {
      __cleanupFailed = true
      __preserveCleanupError(
        __registrationFailed
          ? __registrationError
          : __contextInitializationError,
        error,
      )
      try {
        __retainEmnapiContextCleanupListener()
      } catch (__listenerError) {
        __preserveCleanupError(
          __contextInitializationError,
          __listenerError,
        )
      }
    }
    if (__cleanupResult) {
      void __cleanupResult.then(
        () => {
          try {
            __removeEmnapiContextCleanupListeners()
          } catch (__cleanupError) {
            __preserveCleanupError(
              __contextInitializationError,
              __cleanupError,
            )
          }
        },
        (error) => {
          __preserveCleanupError(
            __registrationFailed
              ? __registrationError
              : __contextInitializationError,
            error,
          )
          try {
            __retainEmnapiContextCleanupListener()
          } catch (__listenerError) {
            __preserveCleanupError(
              __contextInitializationError,
              __listenerError,
            )
          }
        },
      )
    } else if (!__cleanupFailed) {
      try {
        __removeEmnapiContextCleanupListeners()
      } catch (__cleanupError) {
        __preserveCleanupError(
          __contextInitializationError,
          __cleanupError,
        )
      }
    }
  }
  throw __contextInitializationError
}

let __wasmMemory
let __wasiModule
let __nodeTaskHostRegistration
let __nodeTimerHostRegistration
let __napiModule

try {
  __registerEmnapiContextBeforeExit()

  __wasmMemory = new WebAssembly.Memory({
    initial: 1024,
    maximum: 65536,
  })

  let __wasmFilePath = __nodePath.join(__dirname, 'rolldown-binding.wasm32-wasip1.wasm')
  const __wasmDebugFilePath = __nodePath.join(__dirname, 'rolldown-binding.wasm32-wasip1.debug.wasm')

  if (__nodeFs.existsSync(__wasmDebugFilePath)) {
    __wasmFilePath = __wasmDebugFilePath
  } else if (!__nodeFs.existsSync(__wasmFilePath)) {
    const __wasiPackageEntry = require.resolve('@rolldown/binding-wasm32-wasip1')
    const __packagedWasmFilePath = __nodePath.join(
    __nodePath.dirname(__wasiPackageEntry),
    'rolldown-binding.wasm32-wasip1.wasm',
    )
    if (!__nodeFs.existsSync(__packagedWasmFilePath)) {
      throw new Error(
        '@rolldown/binding-wasm32-wasip1 is installed but is missing rolldown-binding.wasm32-wasip1.wasm.',
      )
    }
    __wasmFilePath = __packagedWasmFilePath
  }

  ;({
    instance: __napiInstance,
    module: __wasiModule,
    napiModule: __napiModule,
  } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
    context: __emnapiContext,
  asyncWorkPoolSize: 0,
    wasi: __wasi,
    overwriteImports(importObject) {
      importObject.env = {
        ...importObject.env,
        ...importObject.napi,
        ...importObject.emnapi,
        memory: __wasmMemory,
      }
      return importObject
    },
    beforeInit({ instance }) {
      __napiInstance = instance
      for (const name of Object.keys(instance.exports)) {
        if (name.startsWith('__napi_register__')) {
          instance.exports[name]()
        }
      }
    },
  }))
  // CommonJS can retain these eager exports in its module cache across any
  // number of beforeExit work-resumption cycles. Node provides no terminal
  // beforeExit signal, so a successfully initialized context must remain live
  // until exit. Context.destroy() is synchronous in emnapi's public contract,
  // so terminal cleanup hooks still get a best-effort invocation. A
  // nonconforming thenable cannot be awaited from exit, but is marked handled.
  __handoffEmnapiContextCleanupToExit()
/* ROLLDOWN_CURRENT_THREAD_HOST_BOOTSTRAP_START */
;{
  const __rolldownBinding = __napiModule.exports
  const __getCurrentThreadTaskHostContractVersion =
    __rolldownBinding.getCurrentThreadTaskHostContractVersion
  const __isCurrentThreadHostRegistrationActive =
    __rolldownBinding.isCurrentThreadHostRegistrationActive
  const __registerCurrentThreadTaskHost =
    __rolldownBinding.registerCurrentThreadTaskHost
  const __registerTimerHost = __rolldownBinding.registerTimerHost
  const __reserveCurrentThreadHostRegistration =
    __rolldownBinding.reserveCurrentThreadHostRegistration
  const __unregisterCurrentThreadTaskHost =
    __rolldownBinding.unregisterCurrentThreadTaskHost
  const __unregisterTimerHost = __rolldownBinding.unregisterTimerHost
  if (
    typeof __getCurrentThreadTaskHostContractVersion !== 'function' ||
    typeof __isCurrentThreadHostRegistrationActive !== 'function' ||
    typeof __registerCurrentThreadTaskHost !== 'function' ||
    typeof __registerTimerHost !== 'function' ||
    typeof __reserveCurrentThreadHostRegistration !== 'function' ||
    typeof __unregisterCurrentThreadTaskHost !== 'function' ||
    typeof __unregisterTimerHost !== 'function'
  ) {
    throw new TypeError(
      'The threadless Rolldown binding does not expose its CurrentThread host integration',
    )
  }
  const __taskHostContractVersion =
    Reflect.apply(
      __getCurrentThreadTaskHostContractVersion,
      __rolldownBinding,
      [],
    )
  if (__taskHostContractVersion !== 4) {
    throw new TypeError(
      'The threadless Rolldown binding uses CurrentThread task-host contract version ' +
        String(__taskHostContractVersion) +
        ', but version 4 is required',
    )
  }
  const __readHostRegistration = (__registration, __label) => {
    let __high
    let __low
    try {
      __high = Reflect.get(__registration, 'high', __registration)
      __low = Reflect.get(__registration, 'low', __registration)
    } catch {}
    if (
      !Number.isInteger(__high) ||
      __high < 0 ||
      __high > 0xffffffff ||
      !Number.isInteger(__low) ||
      __low < 0 ||
      __low > 0xffffffff ||
      (__high === 0 && __low === 0)
    ) {
      throw new TypeError(
        'The threadless Rolldown binding returned an invalid ' +
          __label +
          ' host registration',
      )
    }
    return { high: __high, low: __low }
  }
  const __assertHostRegistrationActive = (__registration, __label) => {
    const __active = Reflect.apply(
      __isCurrentThreadHostRegistrationActive,
      __rolldownBinding,
      [__registration.high, __registration.low],
    )
    if (typeof __active !== 'boolean') {
      throw new TypeError(
        'The threadless Rolldown binding returned an invalid ' +
          __label +
          ' host liveness result',
      )
    }
    if (!__active) {
      throw new TypeError(
        'The threadless Rolldown binding returned an inactive ' +
          __label +
          ' host registration',
      )
    }
  }
  const __taskHostRegistration = __readHostRegistration(
    Reflect.apply(
      __reserveCurrentThreadHostRegistration,
      __rolldownBinding,
      [],
    ),
    'task',
  )
  __nodeTaskHostRegistration = __taskHostRegistration
  Reflect.apply(__registerCurrentThreadTaskHost, __rolldownBinding, [
    __taskHostRegistration.high,
    __taskHostRegistration.low,
  ])
  __assertHostRegistrationActive(__taskHostRegistration, 'task')

  const __setTimeoutHost = globalThis.setTimeout?.bind(globalThis)
  const __clearTimeoutHost = globalThis.clearTimeout?.bind(globalThis)
  if (__setTimeoutHost && __clearTimeoutHost) {
    const __MAX_HOST_TIMEOUT_MS = 2147483647
    const __activeTimers = new Map()
    const __armTimer = (__id, __timer) => {
      const __delay = Math.min(__timer.remainingMs, __MAX_HOST_TIMEOUT_MS)
      __timer.handle = __setTimeoutHost(() => {
        if (__activeTimers.get(__id) !== __timer) return
        __timer.remainingMs -= __delay
        if (__timer.remainingMs > 0) {
          try {
            __armTimer(__id, __timer)
          } catch (__error) {
            __activeTimers.delete(__id)
            __timer.reject(__error)
          }
          return
        }
        __activeTimers.delete(__id)
        __timer.resolve()
      }, __delay)
    }
    const __cancelTimer = (__timer) => {
      try {
        if (__timer.handle !== undefined) {
          __clearTimeoutHost(__timer.handle)
        }
      } catch {
        // Rust invokes this callback through a non-catching TSFN. Contain
        // host cancellation failures at the JavaScript boundary.
      } finally {
        __timer.resolve()
      }
    }
    const __timerHostRegistration = __readHostRegistration(
      Reflect.apply(
        __reserveCurrentThreadHostRegistration,
        __rolldownBinding,
        [],
      ),
      'timer',
    )
    __nodeTimerHostRegistration = __timerHostRegistration
    Reflect.apply(__registerTimerHost, __rolldownBinding, [
      __timerHostRegistration.high,
      __timerHostRegistration.low,
      (__id, __ms) => {
        const __previous = __activeTimers.get(__id)
        if (__previous) {
            __activeTimers.delete(__id)
            __cancelTimer(__previous)
          }
          return new Promise((__resolve, __reject) => {
            const __timer = {
              handle: undefined,
              remainingMs: Math.max(__ms, 0),
              reject: __reject,
              resolve: __resolve,
            }
            __activeTimers.set(__id, __timer)
            try {
              __armTimer(__id, __timer)
            } catch (__error) {
              if (__activeTimers.get(__id) === __timer) {
                __activeTimers.delete(__id)
              }
              __reject(__error)
            }
          })
        },
        (__id) => {
          const __timer = __activeTimers.get(__id)
          if (!__timer) return
          __activeTimers.delete(__id)
          __cancelTimer(__timer)
        },
      ])
    __assertHostRegistrationActive(__timerHostRegistration, 'timer')
  }
}
/* ROLLDOWN_CURRENT_THREAD_HOST_BOOTSTRAP_END */
/* ROLLDOWN_NODE_INITIALIZATION_CLEANUP_START */
} catch (__error) {
  const __cleanupErrors = []
  const __cleanupSync = (__operation, __message) => {
    const __operationErrors = []
    for (let __attempt = 0; __attempt < 2; __attempt += 1) {
      try {
        __operation()
        return true
      } catch (__cleanupError) {
        __operationErrors.push(__cleanupError)
      }
    }
    __cleanupErrors.push(new AggregateError(__operationErrors, __message))
    return false
  }
  if (
    typeof __nodeTimerHostRegistration !== 'undefined' &&
    __nodeTimerHostRegistration !== undefined
  ) {
    const __released = __cleanupSync(() => {
      const __binding = __napiModule.exports
      Reflect.apply(__binding.unregisterTimerHost, __binding, [
        __nodeTimerHostRegistration.high,
        __nodeTimerHostRegistration.low,
      ])
    }, 'Threadless Node timer-host cleanup failed')
    if (__released) {
      __nodeTimerHostRegistration = undefined
    }
  }
  if (
    typeof __nodeTaskHostRegistration !== 'undefined' &&
    __nodeTaskHostRegistration !== undefined
  ) {
    const __released = __cleanupSync(() => {
      const __binding = __napiModule.exports
      Reflect.apply(__binding.unregisterCurrentThreadTaskHost, __binding, [
        __nodeTaskHostRegistration.high,
        __nodeTaskHostRegistration.low,
      ])
    }, 'Threadless Node task-host cleanup failed')
    if (__released) {
      __nodeTaskHostRegistration = undefined
    }
  }
  let __cleanupResult
  let __contextCleanupCompleted = false
  const __contextCleanupErrors = []
  for (let __attempt = 0; __attempt < 2; __attempt += 1) {
    try {
      __cleanupResult = __destroyEmnapiContext()
      __contextCleanupCompleted = true
      break
    } catch (__cleanupError) {
      __contextCleanupErrors.push(__cleanupError)
    }
  }
  if (!__contextCleanupCompleted) {
    __cleanupErrors.push(
      new AggregateError(
        __contextCleanupErrors,
        'Threadless Node initialization context cleanup failed',
      ),
    )
    __cleanupSync(
      () => __retainEmnapiContextCleanupListener(),
      'Threadless Node initialization cleanup listener retention failed',
    )
  }
  if (__cleanupResult) {
    void __cleanupResult.then(
      () => {
        try {
          __removeEmnapiContextCleanupListeners()
        } catch (__cleanupError) {
          __preserveCleanupError(__error, __cleanupError)
        }
      },
      (__cleanupError) => {
        __preserveCleanupError(__error, __cleanupError)
        try {
          __retainEmnapiContextCleanupListener()
        } catch (__listenerError) {
          __preserveCleanupError(__error, __listenerError)
        }
      },
    )
  } else if (__contextCleanupCompleted) {
    __cleanupSync(
      () => __removeEmnapiContextCleanupListeners(),
      'Threadless Node initialization cleanup listener removal failed',
    )
  }
  if (__cleanupErrors.length > 0) {
    throw new AggregateError(
      [
        __error,
        new AggregateError(
          __cleanupErrors,
          'Threadless Node initialization cleanup failed',
        ),
      ],
      'Threadless Node initialization failed and cleanup did not complete',
      { cause: __error },
    )
  }
  throw __error
}
/* ROLLDOWN_NODE_INITIALIZATION_CLEANUP_END */
module.exports = __napiModule.exports
module.exports.__rolldownBindingTarget = 'wasi'
module.exports.LegalCommentsMode = __napiModule.exports.LegalCommentsMode
module.exports.minify = __napiModule.exports.minify
module.exports.minifySync = __napiModule.exports.minifySync
module.exports.Severity = __napiModule.exports.Severity
module.exports.ParseResult = __napiModule.exports.ParseResult
module.exports.ExportExportNameKind = __napiModule.exports.ExportExportNameKind
module.exports.ExportImportNameKind = __napiModule.exports.ExportImportNameKind
module.exports.ExportLocalNameKind = __napiModule.exports.ExportLocalNameKind
module.exports.ImportNameKind = __napiModule.exports.ImportNameKind
module.exports.parse = __napiModule.exports.parse
module.exports.parseSync = __napiModule.exports.parseSync
module.exports.rawTransferSupported = __napiModule.exports.rawTransferSupported
module.exports.ResolverFactory = __napiModule.exports.ResolverFactory
module.exports.EnforceExtension = __napiModule.exports.EnforceExtension
module.exports.ModuleType = __napiModule.exports.ModuleType
module.exports.sync = __napiModule.exports.sync
module.exports.HelperMode = __napiModule.exports.HelperMode
module.exports.isolatedDeclaration = __napiModule.exports.isolatedDeclaration
module.exports.isolatedDeclarationSync = __napiModule.exports.isolatedDeclarationSync
module.exports.moduleRunnerTransform = __napiModule.exports.moduleRunnerTransform
module.exports.moduleRunnerTransformSync = __napiModule.exports.moduleRunnerTransformSync
module.exports.transform = __napiModule.exports.transform
module.exports.transformSync = __napiModule.exports.transformSync
module.exports.BindingAsyncRuntimeLease = __napiModule.exports.BindingAsyncRuntimeLease
module.exports.BindingBundleEndEventData = __napiModule.exports.BindingBundleEndEventData
module.exports.BindingBundleErrorEventData = __napiModule.exports.BindingBundleErrorEventData
module.exports.BindingBundler = __napiModule.exports.BindingBundler
module.exports.BindingBundleStartEventData = __napiModule.exports.BindingBundleStartEventData
module.exports.BindingCallableBuiltinPlugin = __napiModule.exports.BindingCallableBuiltinPlugin
module.exports.BindingChunkingContext = __napiModule.exports.BindingChunkingContext
module.exports.BindingDecodedMap = __napiModule.exports.BindingDecodedMap
module.exports.BindingDevEngine = __napiModule.exports.BindingDevEngine
module.exports.BindingLoadPluginContext = __napiModule.exports.BindingLoadPluginContext
module.exports.BindingMagicString = __napiModule.exports.BindingMagicString
module.exports.BindingModuleInfo = __napiModule.exports.BindingModuleInfo
module.exports.BindingNormalizedOptions = __napiModule.exports.BindingNormalizedOptions
module.exports.BindingOutputAsset = __napiModule.exports.BindingOutputAsset
module.exports.BindingOutputChunk = __napiModule.exports.BindingOutputChunk
module.exports.BindingPluginContext = __napiModule.exports.BindingPluginContext
module.exports.BindingRenderedChunk = __napiModule.exports.BindingRenderedChunk
module.exports.BindingRenderedChunkMeta = __napiModule.exports.BindingRenderedChunkMeta
module.exports.BindingRenderedModule = __napiModule.exports.BindingRenderedModule
module.exports.BindingSourceMap = __napiModule.exports.BindingSourceMap
module.exports.BindingTransformPluginContext = __napiModule.exports.BindingTransformPluginContext
module.exports.BindingWatcher = __napiModule.exports.BindingWatcher
module.exports.BindingWatcherBundler = __napiModule.exports.BindingWatcherBundler
module.exports.BindingWatcherChangeData = __napiModule.exports.BindingWatcherChangeData
module.exports.BindingWatcherEvent = __napiModule.exports.BindingWatcherEvent
module.exports.ParallelJsPluginRegistry = __napiModule.exports.ParallelJsPluginRegistry
module.exports.TraceSubscriberGuard = __napiModule.exports.TraceSubscriberGuard
module.exports.TsconfigCache = __napiModule.exports.TsconfigCache
module.exports.acquireAsyncRuntime = __napiModule.exports.acquireAsyncRuntime
module.exports.BindingAttachDebugInfo = __napiModule.exports.BindingAttachDebugInfo
module.exports.BindingBuiltinPluginName = __napiModule.exports.BindingBuiltinPluginName
module.exports.BindingChunkModuleOrderBy = __napiModule.exports.BindingChunkModuleOrderBy
module.exports.BindingErrorStage = __napiModule.exports.BindingErrorStage
module.exports.BindingLogLevel = __napiModule.exports.BindingLogLevel
module.exports.BindingPluginOrder = __napiModule.exports.BindingPluginOrder
module.exports.BindingPropertyReadSideEffects = __napiModule.exports.BindingPropertyReadSideEffects
module.exports.BindingPropertyWriteSideEffects = __napiModule.exports.BindingPropertyWriteSideEffects
module.exports.BindingRebuildStrategy = __napiModule.exports.BindingRebuildStrategy
module.exports.BindingRuntimeFlavor = __napiModule.exports.BindingRuntimeFlavor
module.exports.collapseSourcemaps = __napiModule.exports.collapseSourcemaps
module.exports.configureAsyncRuntime = __napiModule.exports.configureAsyncRuntime
module.exports.enhancedTransform = __napiModule.exports.enhancedTransform
module.exports.enhancedTransformSync = __napiModule.exports.enhancedTransformSync
module.exports.FilterTokenKind = __napiModule.exports.FilterTokenKind
module.exports.getAsyncRuntimeConfig = __napiModule.exports.getAsyncRuntimeConfig
module.exports.getAsyncRuntimeMetrics = __napiModule.exports.getAsyncRuntimeMetrics
module.exports.getCurrentThreadTaskHostContractVersion = __napiModule.exports.getCurrentThreadTaskHostContractVersion
module.exports.getRuntimeCapabilities = __napiModule.exports.getRuntimeCapabilities
module.exports.initTraceSubscriber = __napiModule.exports.initTraceSubscriber
module.exports.isCurrentThreadHostRegistrationActive = __napiModule.exports.isCurrentThreadHostRegistrationActive
module.exports.registerCurrentThreadTaskHost = __napiModule.exports.registerCurrentThreadTaskHost
module.exports.registerPlugins = __napiModule.exports.registerPlugins
module.exports.registerTimerHost = __napiModule.exports.registerTimerHost
module.exports.reserveCurrentThreadHostRegistration = __napiModule.exports.reserveCurrentThreadHostRegistration
module.exports.resetAsyncRuntimeMetrics = __napiModule.exports.resetAsyncRuntimeMetrics
module.exports.resolveTsconfig = __napiModule.exports.resolveTsconfig
module.exports.shutdownAsyncRuntime = __napiModule.exports.shutdownAsyncRuntime
module.exports.startAsyncRuntime = __napiModule.exports.startAsyncRuntime
module.exports.unregisterCurrentThreadTaskHost = __napiModule.exports.unregisterCurrentThreadTaskHost
module.exports.unregisterTimerHost = __napiModule.exports.unregisterTimerHost
