/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InputOptions {
  input: Record<string, string>
  preserveSymlinks: boolean
  shimMissingExports: boolean
  treeshake?: boolean
  cwd: string
}
export interface OutputOptions {
  entryFileNames?: string
  chunkFileNames?: string
  dir?: string
  exports?: 'default' | 'named' | 'none' | 'auto'
  format?: 'esm' | 'cjs'
}
export interface OutputChunk {
  code: string
  fileName: string
}
export class Bundler {
  constructor(inputOpts: InputOptions)
  write(opts: OutputOptions): Promise<Array<OutputChunk>>
  generate(opts: OutputOptions): Promise<Array<OutputChunk>>
}
