import type { Plugin, SourceMap } from 'rolldown';
import { defineTest } from 'rolldown-tests';
import { expect } from 'vitest';

// With `experimental.nativeMagicString`, the map of a transform that returns a
// native MagicString is generated by a background worker. `getCombinedSourcemap`
// in a later hook must still include it, instead of mapping the transformed code
// to itself.
let originalCode: string | undefined;
const combined: SourceMap[] = [];

const prependLine = (name: string, line: string): Plugin => ({
  name,
  transform(code, id, meta) {
    if (!id.endsWith('main.js')) return null;
    originalCode ??= code;
    meta.magicString!.prepend(line);
    return { code: meta.magicString! };
  },
});

const probe = (name: string): Plugin => ({
  name,
  transform(_code, id) {
    if (!id.endsWith('main.js')) return null;
    combined.push(this.getCombinedSourcemap());
    return null;
  },
});

export default defineTest({
  config: {
    input: ['main.js'],
    experimental: {
      nativeMagicString: true,
    },
    output: {
      sourcemap: true,
    },
    plugins: [
      prependLine('prepend-1', '// line 1\n'),
      probe('probe-1'),
      prependLine('prepend-2', '// line 2\n'),
      probe('probe-2'),
    ],
  },
  afterTest() {
    expect(combined).toHaveLength(2);
    // Both maps point back at the original source, shifted down by the lines
    // prepended so far.
    expect(combined[0].sourcesContent).toStrictEqual([originalCode]);
    expect(combined[0].mappings).toBe(';AAAA;AACA');
    expect(combined[1].sourcesContent).toStrictEqual([originalCode]);
    expect(combined[1].mappings).toBe(';;AAAA;AACA');
  },
});
