name: Security Analysis

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: oxc-project/security-action@4211cd3f56ba742507263ea4a999f3be4165a53c # v1.0.1
