name: Prepare Release

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # Every Wednesday at 8am Shanghai time (UTC+8 = 00:00 UTC)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for create-pull-request
      pull-requests: write # for create-pull-request
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0 # for changelog
          persist-credentials: true # for create-pull-request

      - uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
        with:
          tool: just

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Get and bump version
        run: |
          VERSION=$(node -e "
            const pkg = require('./packages/rolldown/package.json');
            const [, base, beta] = pkg.version.match(/^(\d+\.\d+\.\d+)-beta\.(\d+)$/);
            console.log(\`\${base}-beta.\${parseInt(beta) + 1}\`);
          ")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: just bump-packages ${VERSION}

      - name: Regenerate binding.js after version bump
        run: pnpm --filter rolldown build-binding

      - name: Generate changelog via git cliff
        id: changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # v4.7.0
        env:
          # Used to make request to GitHub without ratelimits.
          # `secrets.GIT_CLIFF_TOKEN` only has read permission.
          GITHUB_TOKEN: ${{ secrets.GIT_CLIFF_TOKEN }}
        with:
          version: v2.9.1 # git cliff version
          config: cliff.toml
          args: --unreleased --prepend CHANGELOG.md --tag ${{ env.VERSION }}

      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        if: ${{ steps.changelog.outputs.content }}
        with:
          add-paths: |
            CHANGELOG.md
            packages/**/package.json
            packages/rolldown/src/binding.cjs
          commit-message: 'release: v${{ env.VERSION }}'
          body: ${{ steps.changelog.outputs.content }}
          branch: release-v${{ env.VERSION }}
          branch-suffix: timestamp
          base: main
          title: 'release: v${{ env.VERSION }}'
          assignees: Boshen, shulaoda
