name: Rust Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ inputs.changed }}
    name: Cargo Test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@83350c0ef69ec34f00be596f1cb9302179b9f43d # v1.0.9
        with:
          tools: just
          cache-key: debug-build

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Build
        run: cargo test --workspace --exclude rolldown_binding --no-run

      - name: Run Test
        run: just test-rust
        env:
          # Reject updated snapshots https://insta.rs/docs/advanced/#controlling-snapshot-updating
          INSTA_UPDATE: no
