name: Node Dev Server Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Node Dev Server Test (Node ${{ matrix.node-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ inputs.os == 'ubuntu-latest' && fromJson('[20, 22, 24]') || fromJson('[24]') }}
    steps:
      - name: Skip dev server test when no node changes
        if: ${{ !inputs.changed }}
        run: echo "No Node.js changes detected; skipping dev server tests."

      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0
        if: ${{ inputs.changed }}

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6
        if: ${{ inputs.changed }}

      - name: Download Native Rolldown Build
        if: ${{ inputs.changed }}
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: rolldown-native-${{ inputs.os }}
          path: ./packages

      - name: Build `@rolldown/test-dev-server`
        if: ${{ inputs.changed }}
        run: pnpm --filter '@rolldown/test-dev-server' build

      - name: Install Playwright
        if: ${{ inputs.changed }}
        run: pnpm playwright install chromium

      - name: Setup Node${{ matrix.node-version }} For Testing
        if: ${{ inputs.changed }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Dev Server Test
        if: ${{ inputs.changed }}
        run: pnpm run --filter '@rolldown/test-dev-server-tests' test
