name: Node Dev Server Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean
      node-version:
        required: true
        type: number

jobs:
  run:
    name: Node Dev Server Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os == 'ubuntu-latest' && 'namespace-profile-linux-x64-default' || inputs.os == 'macos-latest' && 'namespace-profile-mac-default' || inputs.os }}
    timeout-minutes: 15
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: voidzero-dev/setup-vp@56918a6d0c629c55ae8b88826a7d47fda85769ee # v1.9.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: true

      - name: Download Native Rolldown Build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: rolldown-native-${{ inputs.os }}
          path: packages/rolldown/dist

      - name: Build `@rolldown/test-dev-server`
        run: vp run --filter '@rolldown/test-dev-server' build

      - name: Install Playwright
        run: vp exec playwright install chromium

      - name: Dev Server Test
        run: vp run --filter '@rolldown/test-dev-server-tests' test
