name: Node Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean
      node-version:
        required: true
        type: number

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - uses: samypr100/setup-dev-drive@30f0f98ae5636b2b6501e181dfb3631b9974818d # v4.0.0
        if: runner.os == 'Windows'
        with:
          drive-size: 12GB
          drive-format: ReFS
          env-mapping: |
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm

      - uses: oxc-project/setup-node@b8d296d30eafd1ae2968fab67aead472a1dbf6d4 # v1.0.7

      - name: Download Native Rolldown Build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: rolldown-native-${{ inputs.os }}
          path: ./packages

      - name: Build `@rolldown/test-dev-server`
        run: pnpm --filter '@rolldown/test-dev-server' build

      - name: Setup Node${{ inputs.node-version }} For Testing
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ inputs.node-version }}
          package-manager-cache: false

      - name: Node Test
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test
        run: pnpm run --filter rollup-tests test
        env:
          SKIP_PASS_DIFF: ${{ inputs.node-version != 24 && '1' || '' }}

      - name: Build Examples
        run: pnpm --filter '@example/**' build
