name: Node Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Node Test (Node ${{ matrix.node-version }})
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ inputs.os == 'ubuntu-latest' && fromJson('[20, 22, 24]') || fromJson('[24]') }}
    steps:
      - name: Skip node test when no node changes
        if: ${{ !inputs.changed }}
        run: echo "No Node.js changes detected; skipping node tests."

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ inputs.changed }}
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - uses: samypr100/setup-dev-drive@30f0f98ae5636b2b6501e181dfb3631b9974818d # v4.0.0
        if: ${{ inputs.changed && runner.os == 'Windows' }}
        with:
          drive-size: 12GB
          drive-format: ReFS
          env-mapping: |
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6
        if: ${{ inputs.changed }}

      - name: Download Native Rolldown Build
        if: ${{ inputs.changed }}
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: rolldown-native-${{ inputs.os }}
          path: ./packages

      - name: Build `@rolldown/test-dev-server`
        if: ${{ inputs.changed }}
        run: pnpm --filter '@rolldown/test-dev-server' build

      - name: Setup Node${{ matrix.node-version }} For Testing
        if: ${{ inputs.changed }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Node Test
        if: ${{ inputs.changed }}
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test
        if: ${{ inputs.changed }}
        run: pnpm run --filter rollup-tests test
        env:
          SKIP_PASS_DIFF: ${{ matrix.node-version != 24 && '1' || '' }}

      - name: Build Examples
        if: ${{ inputs.changed }}
        run: pnpm --filter '@example/**' build
