name: Rust Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ inputs.changed }}
    name: Cargo Test
    runs-on: ${{ inputs.os == 'ubuntu-latest' && 'namespace-profile-linux-x64-default' || inputs.os == 'macos-latest' && 'namespace-profile-mac-default' || inputs.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - uses: samypr100/setup-dev-drive@30f0f98ae5636b2b6501e181dfb3631b9974818d # v4.0.0
        if: runner.os == 'Windows'
        with:
          drive-size: 20GB
          drive-format: ReFS
          env-mapping: |
            CARGO_HOME,{{ DEV_DRIVE }}/.cargo
            RUSTUP_HOME,{{ DEV_DRIVE }}/.rustup
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm

      - name: Setup Rust
        uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          tools: just
          cache-key: cargo-test
          save-cache: ${{ github.ref_name == 'main' }}
          target-dir: ${{ runner.os == 'Windows' && format('{0}/target', env.DEV_DRIVE) || '' }}

      - uses: voidzero-dev/setup-vp@56918a6d0c629c55ae8b88826a7d47fda85769ee # v1.9.0
        with:
          cache: true

      - name: Run Test
        run: just test-rust
        env:
          # Reject updated snapshots https://insta.rs/docs/advanced/#controlling-snapshot-updating
          INSTA_UPDATE: no

      - name: Cache esbuild snapshots
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: scripts/tmp/esbuild-tests/snapshots
          key: esbuild-snapshots-${{ hashFiles('scripts/src/esbuild-tests/urls.ts') }}

      - name: Check if esbuild tests diff has changed
        run: |
          just ued
          git diff --exit-code
