name: Node Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean
      node-version:
        required: true
        type: number

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os == 'ubuntu-latest' && 'namespace-profile-linux-x64-default' || inputs.os == 'macos-latest' && 'namespace-profile-mac-default' || inputs.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - uses: samypr100/setup-dev-drive@30f0f98ae5636b2b6501e181dfb3631b9974818d # v4.0.0
        if: runner.os == 'Windows'
        with:
          drive-size: 12GB
          drive-format: ReFS
          env-mapping: |
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm

      - uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6 # v1.8.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: true

      - name: Download Native Rolldown Build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: rolldown-native-${{ inputs.os }}
          path: ./packages

      - name: Build `@rolldown/test-dev-server`
        run: vp run --filter '@rolldown/test-dev-server' build

      - name: Node Test
        run: |
          vp run --filter rolldown-tests test:main && vp run --filter rolldown-tests test:watcher && vp run --filter rolldown-tests test:stability

      - name: Rollup Test
        run: vp run --filter rollup-tests test
        env:
          SKIP_PASS_DIFF: ${{ inputs.node-version != 24 && '1' || '' }}

      - name: Build Examples
        run: vp run --filter '@example/**' build
