name: Reusable Rolldown Native Build

permissions: {}

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: boolean
      os:
        required: true
        type: string

jobs:
  run:
    name: Build Rolldown Native
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os == 'ubuntu-latest' && 'namespace-profile-linux-x64-default' || inputs.os == 'macos-latest' && 'namespace-profile-mac-default' || inputs.os }}
    timeout-minutes: 15
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: samypr100/setup-dev-drive@30f0f98ae5636b2b6501e181dfb3631b9974818d # v4.0.0
        if: runner.os == 'Windows'
        with:
          drive-size: 12GB
          drive-format: ReFS
          env-mapping: |
            CARGO_HOME,{{ DEV_DRIVE }}/.cargo
            RUSTUP_HOME,{{ DEV_DRIVE }}/.rustup
            PNPM_HOME,{{ DEV_DRIVE }}/.pnpm

      - name: Setup Rust
        uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          tools: just
          cache-key: native-build
          save-cache: ${{ github.ref_name == 'main' }}
          target-dir: ${{ runner.os == 'Windows' && format('{0}/target', env.DEV_DRIVE) || '' }}

      - uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6 # v1.8.0
        with:
          cache: true

      - name: Build Native Rolldown
        run: just build-rolldown

      - name: Check no diff
        run: git diff --exit-code

      - name: Upload Rolldown Native
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rolldown-native-${{ inputs.os }}
          path: |
            packages/rolldown/dist
            packages/pluginutils/dist
          if-no-files-found: error
